# This is an example that presents the use of repetition structures in the Python language
# Este é um exemplo que apresenta o uso das estruturas de repetição na linguagem  Python

# Line 1 >> Start of the for loop. The variable 'i' will be used to iterate over a sequence of numbers. The function range() generates the sequence of integers from 0 to 9. # Início do loop for. A variavel 'i' será utilizada para iterar sobre uma sequência de números. A função range() gera a sequência de números inteiros de 0 até 9.
# Line 2 >> The instruction print(i) displays the value inside the parentheses in the console. With i takes each value of the sequence generated by range(0, 10), the output will be: 0,1,2,3,4,5,6,7,8,9. # A instrução print(i) exibe no console, o valor que está dentro dos parênteses. Como i assume cada valor da sequência gerada por range(0, 10), a saída será: 0,1,2,3,4,5,6,7,8,9.
for i in range(0, 10):  
    print(i)  


